version: '2'

services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8080:8080
            - 8081:8081
            - 8082:8082
            - 8083:8083
        restart: always

    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always

    apache:
        depends_on:
            - reverseproxy
        image: httpd:alpine
        restart: always

    apache2:
        depends_on:
            - reverseproxy
        image: httpd:alpine
        restart: always

    hello:
        depends_on:
            - reverseproxy
        image: tutum/hello-world
        restart: always
