# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


jobs:
- job: win2016
  pool:
    vmImage: 'vs2017-win2016'
  steps: 
  - powershell: |
      Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
  - task: PowerShell@2
    inputs:
      filePath: 'ud-docker/dockerbuild.ps1'
      arguments: '-WindowsVersion 2016'

- job: winLatest
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      Write-Host 'listing PackageProviders..'
      Get-PackageProvider

      Write-Host 'updating Pester..'
      Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser

      Write-Host 'listing dotnet runtime..'
      dotnet --list-runtimes

  - task: PowerShell@2
    inputs:
      filePath: 'ud-docker/dockerbuild.ps1'
      arguments: '-WindowsVersion 2019'
