# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


jobs:
- job: 2016
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: |
      (Get-ItemProperty 'HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full').Release

  - task: PowerShell@2
    inputs:
      filePath: 'ud-docker/dockerbuild.ps1'

- job: Latest
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      (Get-ItemProperty 'HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full').Release

  - task: PowerShell@2
    inputs:
      filePath: 'ud-docker/dockerbuild.ps1'
