# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


jobs:
- job: win2016
  pool:
    vmImage: 'vs2017-win2016'
  steps: 
  - powershell: |
      Get-ComputerInfo | select WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer
      Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
    displayName: Setup
  - task: PowerShell@2
    inputs:
      filePath: 'ud-docker/dockerbuild.ps1'
      arguments: '-WindowsVersion 2016'

- job: winLatest
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      Get-ComputerInfo | select WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer
      Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
    displayName: Setup

  - task: PowerShell@2
    inputs:
      filePath: 'ud-docker/dockerbuild.ps1'
      arguments: '-WindowsVersion 2019'
